M48
; DRILL file {KiCad 7.0.4} date Sun 28 May 2023 10:47:31 AM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-28T10:47:31+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.5669Y-2.3031
X4.5669Y-2.9724
X7.2441Y-2.3031
X7.2441Y-2.9724
T0
M30
